name: Run pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: astral-sh/setup-uv
        with:
          enable-cache: true

      - name: Test
        run: |
          uv sync --all-extras --all-groups
          uv run pytest -v
